# Generated by Django 5.1.4 on 2025-01-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tags",
        ),
    ]
