# Generated by Django 5.1.4 on 2025-01-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image_path",
            field=models.FilePathField(
                blank=True, null=True, path="media/imdb_images_downloads/"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
