# Generated by Django 5.1.4 on 2025-01-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_news_image_path_alter_news_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
