# Generated by Django 5.1.4 on 2025-01-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myfirstapp", "0006_student2_gender_student2_upload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="age",
            field=models.IntegerField(default=18),
        ),
    ]
